import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  screen: { flex: 1 },
  header: { flexDirection: "row", alignItems: "center", paddingBottom: 8 },
  headerTitle: {},
  centerFill: { flex: 1, alignItems: "center", justifyContent: "center" },
  scroll: { flex: 1 },
  body: { paddingTop: 8, paddingBottom: 40 },
  row: { flexDirection: "row", alignItems: "center" },
  spaceBetween: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  microLabel: { fontSize: 11, fontWeight: "800", letterSpacing: 1 },
  barTrack: { height: 6, borderRadius: 999, overflow: "hidden", width: "100%" },
  barFill: { height: "100%", borderRadius: 999 },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    height: 40,
    borderRadius: 12,
    borderWidth: 1,
  },
  searchInput: { flex: 1, padding: 0 },
  clearButton: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  allMineButton: {
    paddingHorizontal: 14,
    justifyContent: "center",
    height: 40,
  },
  itemCard: { padding: 12 },
  nameInput: { flex: 1, paddingHorizontal: 14, paddingVertical: 12 },
  itemNameInput: { padding: 0 },
  itemSplitChip: { paddingHorizontal: 10, paddingVertical: 6 },
  deleteButton: { marginLeft: "auto", padding: 4 },
  feeDeleteButton: { padding: 4 },
  checkbox: {
    width: 22,
    height: 22,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
  },
  addItem: { flexDirection: "row", alignItems: "center", gap: 6 },
  divider: { height: StyleSheet.hairlineWidth },
  categoryPill: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
    justifyContent: "center",
  },
  footer: {},
  confirm: { alignItems: "center" },
  backToItems: { alignItems: "center", paddingVertical: 6 },
  bulkBar: { padding: 12 },
  sheetTitle: { marginBottom: 12 },
  selectToggle: {
    height: 30,
    paddingHorizontal: 12,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
  },
  bucketRow: { flexDirection: "row", alignItems: "center" },
  badge: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
  },
});
